### ISSUE TITLE
/build-image.sh ,  'Connection time-out' error

### ISSUE THREAD

**Issue by jxlijunhao** [JoeWoo/hadoop-spark-hive-cluster-docker#1]
Step 1 : MAINTAINER JoeWoo 0wujian0@gmail.com
 ---> Using cache
 ---> 1d7a4564f35f
Step 2 : RUN yum install -y unzip curl dnsmasq
 ---> Running in 516eaea90450
Loaded plugins: fastestmirror
Setting up Install Process
http://mirrors.aliyun.com/centos/6.7/os/x86_64/repodata/repomd.xml: [Errno 12] Timeout on http://mirrors.aliyun.com/centos/6.7/os/x86_64/repodata/repomd.xml: (28, 'Connection time-out')
Trying other mirror.

http://mirrors.163.com/centos/6.7/os/x86_64/repodata/repomd.xml: [Errno 14] PYCURL ERROR 6 - "Couldn't resolve host 'mirrors.163.com'"
Trying other mirror.
http://centos.ustc.edu.cn/centos/6.7/os/x86_64/repodata/repomd.xml: [Errno 14] PYCURL ERROR 6 - "Couldn't resolve host 'centos.ustc.edu.cn'"
Trying other mirror.

**Comment by JoeWoo** [comment]
check your network and try again... `yum install` is a basic service of CentOS.
