### ISSUE TITLE
Small modifications

### ISSUE THREAD

**Issue by yijia2413** [JoeWoo/hadoop-spark-hive-cluster-docker#2]
Hi @JoeWoo ,  I've just used your cluster for my testing of spark and hive, and I have find some problems.

- [x] ssh keep asking permission when running start-xxx.sh
- [x] hiveserver2 won't start with your current nohup script

**Comment by JoeWoo** [comment]
Sorry for my too late reply. Great job! all changes accepeted. 
Create the PR when you are available.
