### ISSUE TITLE
Unable to ssh between containers

### ISSUE THREAD

**Issue by Hiteshm01** [JoeWoo/hadoop-spark-hive-cluster-docker#4]
I tried building the containers with minor changes. I am able to verify serf members using 
```
root@master:~# serf members
master.bdp.com  172.17.0.2:7946  alive
mysql.bdp.com   172.17.0.3:7946  alive
slave1.bdp.com  172.17.0.4:7946  alive
slave2.bdp.com  172.17.0.5:7946  alive
```
However, on trying ssh, I encountered this
```
root@master:~# ssh slave1.bdp.com
ssh: connect to host slave1.bdp.com port 22: Connection refused
root@master:~#
```

Any idea what am I missing? 

My changes are in this fork https://github.com/hiteshm01/hadoop-spark-hive-cluster-docker.

**Comment by Hiteshm01** [comment]
I was able to solve it via starting ssh service in base container using 
```
service ssh start
```
Though, I am not sure how it was working here before this addition.

**Comment by JoeWoo** [comment]
I cannot reproduce this issue in my Kitematic 0.10.2.  Could you give me more information about your environment?
